export const livingAreas = [
    {
      src: "/LivingArea1.jpg",
      alt: "Living Area 1",
      title: "Modern Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "/LivingArea2.jpg",
      alt: "Living Area 2",
      title: "Modern Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "/LivingArea3.jpg",
      alt: "Living Area 3",
      title: "Modern Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "/LivingArea4.jpg",
      alt: "Living Area 4",
      title: "Modern Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "/LivingArea5.jpg",
      alt: "Living Area 5",
      title: "Modern Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "/LivingArea6.jpg",
      alt: "Living Area 6",
      title: "Modern Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "/LivingArea7.jpg",
      alt: "Living Area 7",
      title: "Modern Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "/LivingArea8.jpg",
      alt: "Living Area 8",
      title: "Modern Living Area",
      description: "Decor / Architecture",
    },
    // Additional entries
    {
      src: "https://images.pexels.com/photos/27640109/pexels-photo-27640109/free-photo-of-a-living-room-with-a-coffee-table-two-chairs-and-a-lamp.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 9",
      title: "Contemporary Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/5982764/pexels-photo-5982764.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 10",
      title: "Rustic Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/1066634/pexels-photo-1066634.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 11",
      title: "Industrial Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/12119218/pexels-photo-12119218.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 12",
      title: "Minimalist Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3935351/pexels-photo-3935351.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 13",
      title: "Modern Farmhouse Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/7101534/pexels-photo-7101534.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 14",
      title: "Elegant Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/8894805/pexels-photo-8894805.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 15",
      title: "Vintage Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3773584/pexels-photo-3773584.png?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 16",
      title: "Luxury Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3773582/pexels-photo-3773582.png?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 17",
      title: "Open Concept Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/27359996/pexels-photo-27359996/free-photo-of-a-living-room-with-a-couch-coffee-table-and-lamp.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 18",
      title: "Scandinavian Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/9890656/pexels-photo-9890656.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 19",
      title: "Transitional Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3457299/pexels-photo-3457299.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 20",
      title: "Traditional Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/5502229/pexels-photo-5502229.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 21",
      title: "Modern Classic Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3773570/pexels-photo-3773570.png?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 22",
      title: "Eclectic Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3935324/pexels-photo-3935324.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 23",
      title: "Urban Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3935330/pexels-photo-3935330.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 24",
      title: "Farmhouse Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/8031899/pexels-photo-8031899.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 25",
      title: "Small Space Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/2121120/pexels-photo-2121120.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 26",
      title: "Gourmet Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/4112236/pexels-photo-4112236.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 27",
      title: "Luxury Modern Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3773572/pexels-photo-3773572.png?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 28",
      title: "Compact Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/1148955/pexels-photo-1148955.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 29",
      title: "Stylish Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/8894805/pexels-photo-8894805.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 30",
      title: "Smart Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/4112601/pexels-photo-4112601.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 31",
      title: "Contemporary Farmhouse Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/312029/pexels-photo-312029.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 32",
      title: "Elegant Modern Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/1909752/pexels-photo-1909752.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 33",
      title: "Industrial Chic Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/7533851/pexels-photo-7533851.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 34",
      title: "Luxury Traditional Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/7533848/pexels-photo-7533848.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 35",
      title: "Modern Minimalist Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/8894804/pexels-photo-8894804.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Living Area 36",
      title: "Rustic Modern Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3753436/pexels-photo-3753436.jpeg?auto=compress&cs=tinysrgb&w=600",
      alt: "Living Area 37",
      title: "Sleek Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/2343468/pexels-photo-2343468.jpeg?auto=compress&cs=tinysrgb&w=600",
      alt: "Living Area 38",
      title: "Urban Modern Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6636291/pexels-photo-6636291.jpeg?auto=compress&cs=tinysrgb&w=600",
      alt: "Living Area 39",
      title: "Classic Contemporary Living Area",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6207939/pexels-photo-6207939.jpeg?auto=compress&cs=tinysrgb&w=600",
      alt: "Living Area 40",
      title: "Vintage Modern Living Area",
      description: "Decor / Architecture",
    },
  ];

export const kitchenData = [
    {
      src: "/kitchen1.jpg",
      alt: "Kitchen 1",
      title: "Modern Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "/kitchen2.jpg",
      alt: "Kitchen 2",
      title: "Modern Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "/kitchen3.jpg",
      alt: "Kitchen 3",
      title: "Modern Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "/kitchen4.jpg",
      alt: "Kitchen 4",
      title: "Modern Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "/kitchen5.jpg",
      alt: "Kitchen 5",
      title: "Modern Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "/kitchen6.jpg",
      alt: "Kitchen 6",
      title: "Modern Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "/kitchen7.jpg",
      alt: "Kitchen 7",
      title: "Modern Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "/kitchen8.jpg",
      alt: "Kitchen 8",
      title: "Modern Kitchen",
      description: "Decor / Architecture",
    },
    // Additional entries
    {
      src: "https://images.pexels.com/photos/10258623/pexels-photo-10258623.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
      alt: "Kitchen 9",
      title: "Contemporary Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/18038082/pexels-photo-18038082/free-photo-of-a-modern-kitchen-design.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 10",
      title: "Rustic Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/7033835/pexels-photo-7033835.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 11",
      title: "Industrial Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3935350/pexels-photo-3935350.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 12",
      title: "Minimalist Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3773579/pexels-photo-3773579.png?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 13",
      title: "Modern Farmhouse Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/11439366/pexels-photo-11439366.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 14",
      title: "Elegant Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/4713253/pexels-photo-4713253.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 15",
      title: "Vintage Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/10222270/pexels-photo-10222270.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 16",
      title: "Luxury Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6636314/pexels-photo-6636314.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 17",
      title: "Open Concept Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/5644353/pexels-photo-5644353.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 18",
      title: "Scandinavian Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/7601088/pexels-photo-7601088.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 19",
      title: "Transitional Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6127212/pexels-photo-6127212.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 20",
      title: "Traditional Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/4221390/pexels-photo-4221390.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 21",
      title: "Modern Classic Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/5825693/pexels-photo-5825693.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 22",
      title: "Eclectic Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/5825699/pexels-photo-5825699.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 23",
      title: "Urban Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/12954265/pexels-photo-12954265.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 24",
      title: "Farmhouse Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/25568754/pexels-photo-25568754/free-photo-of-interior-of-a-modern-kitchen-with-a-table-in-the-middle.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 25",
      title: "Small Space Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6890399/pexels-photo-6890399.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 26",
      title: "Gourmet Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/15848137/pexels-photo-15848137/free-photo-of-kitchen-with-living-room.png?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 27",
      title: "Luxury Modern Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6585627/pexels-photo-6585627.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 28",
      title: "Compact Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/11018252/pexels-photo-11018252.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 29",
      title: "Stylish Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6905780/pexels-photo-6905780.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 30",
      title: "Smart Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/18038066/pexels-photo-18038066/free-photo-of-a-modern-kitchen-with-a-kitchen-island-in-the-middle.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 31",
      title: "Contemporary Farmhouse Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6508354/pexels-photo-6508354.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 32",
      title: "Elegant Modern Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/4119841/pexels-photo-4119841.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 33",
      title: "Industrial Chic Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6303113/pexels-photo-6303113.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 34",
      title: "Luxury Traditional Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/24461265/pexels-photo-24461265/free-photo-of-dining-room-and-kitchen-in-house.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 35",
      title: "Modern Minimalist Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/5071128/pexels-photo-5071128.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 36",
      title: "Rustic Modern Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/8584021/pexels-photo-8584021.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 37",
      title: "Sleek Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/7587861/pexels-photo-7587861.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 38",
      title: "Urban Modern Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6905772/pexels-photo-6905772.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 39",
      title: "Classic Contemporary Kitchen",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/7601071/pexels-photo-7601071.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Kitchen 40",
      title: "Vintage Modern Kitchen",
      description: "Decor / Architecture",
    },
  ];

export const bedRooms = [
    {
      src: "/bedroom1.png",
      alt: "Bedroom 1",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "/bedroom2.png",
      alt: "Bedroom 2",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "/bedroom3.png",
      alt: "Bedroom 3",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "/bedroom4.png",
      alt: "Bedroom 4",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "/bedroom5.png",
      alt: "Bedroom 5",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "/bedroom6.png",
      alt: "Bedroom 6",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "/bedroom7.png",
      alt: "Bedroom 7",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "/bedroom8.png",
      alt: "Bedroom 8",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/3932930/pexels-photo-3932930.jpeg?auto=compress&cs=tinysrgb&w=600",
      alt: "Bedroom 9",
      title: "Elegant Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/462235/pexels-photo-462235.jpeg?auto=compress&cs=tinysrgb&w=600",
      alt: "Bedroom 10",
      title: "Trendy Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/4050423/pexels-photo-4050423.jpeg?auto=compress&cs=tinysrgb&w=600",
      alt: "Bedroom 11",
      title: "Comfortable Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/1329711/pexels-photo-1329711.jpeg?auto=compress&cs=tinysrgb&w=600",
      alt: "Bedroom 12",
      title: "Serene Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/4112558/pexels-photo-4112558.jpeg?auto=compress&cs=tinysrgb&w=600",
      alt: "Bedroom 13",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg?auto=compress&cs=tinysrgb&w=600",
      alt: "Bedroom 14",
      title: "Luxurious Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/1034584/pexels-photo-1034584.jpeg?auto=compress&cs=tinysrgb&w=600",
      alt: "Bedroom 15",
      title: "Sophisticated Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6782577/pexels-photo-6782577.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 16",
      title: "Bright Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6782468/pexels-photo-6782468.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 17",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6480198/pexels-photo-6480198.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 18",
      title: "Elegant Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/7019019/pexels-photo-7019019.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 19",
      title: "Contemporary Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6588577/pexels-photo-6588577.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 20",
      title: "Comfortable Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6588581/pexels-photo-6588581.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 21",
      title: "Chic Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6782472/pexels-photo-6782472.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 22",
      title: "Stylish Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6585749/pexels-photo-6585749.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 23",
      title: "Serene Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6782473/pexels-photo-6782473.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 24",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6585757/pexels-photo-6585757.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 25",
      title: "Luxurious Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6782439/pexels-photo-6782439.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 26",
      title: "Sophisticated Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/5953786/pexels-photo-5953786.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 27",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6588571/pexels-photo-6588571.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 28",
      title: "Elegant Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6538893/pexels-photo-6538893.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 29",
      title: "Trendy Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6585746/pexels-photo-6585746.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 30",
      title: "Chic Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6538895/pexels-photo-6538895.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 31",
      title: "Comfortable Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6480201/pexels-photo-6480201.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 32",
      title: "Stylish Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6444258/pexels-photo-6444258.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 33",
      title: "Cozy Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6587902/pexels-photo-6587902.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 34",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/7019011/pexels-photo-7019011.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 35",
      title: "Elegant Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6782467/pexels-photo-6782467.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 36",
      title: "Comfortable Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6444252/pexels-photo-6444252.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 37",
      title: "Luxurious Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6480212/pexels-photo-6480212.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 38",
      title: "Modern Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/5490380/pexels-photo-5490380.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 39",
      title: "Chic Bedroom",
      description: "Decor / Architecture",
    },
    {
      src: "https://images.pexels.com/photos/6538905/pexels-photo-6538905.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load",
      alt: "Bedroom 40",
      title: "Stylish Bedroom",
      description: "Decor / Architecture",
    },
  ];

export const bathRooms = [
    // First 8 local images
    { src: "/bathroom1.jpg", alt: "Bathroom 1", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "/bathroom2.jpg", alt: "Bathroom 2", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "/bathroom3.jpg", alt: "Bathroom 3", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "/bathroom4.jpg", alt: "Bathroom 4", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "/bathroom5.jpg", alt: "Bathroom 5", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "/bathroom6.jpg", alt: "Bathroom 6", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "/bathroom7.jpg", alt: "Bathroom 7", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "/bathroom8.jpg", alt: "Bathroom 8", title: "Modern Bathroom", description: "Decor / Architecture" },
    
    // Next 32 random images from Unsplash
    { src: "https://images.pexels.com/photos/7168015/pexels-photo-7168015.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 9", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/7147283/pexels-photo-7147283.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 10", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/7018825/pexels-photo-7018825.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1", alt: "Bathroom 11", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/7018821/pexels-photo-7018821.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 12", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6283974/pexels-photo-6283974.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 13", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6934227/pexels-photo-6934227.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 14", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6933766/pexels-photo-6933766.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 15", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6933774/pexels-photo-6933774.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 16", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6580217/pexels-photo-6580217.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 17", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6933772/pexels-photo-6933772.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 18", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/7166551/pexels-photo-7166551.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 19", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6933779/pexels-photo-6933779.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 20", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6934237/pexels-photo-6934237.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 21", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6934225/pexels-photo-6934225.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 22", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6283959/pexels-photo-6283959.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 23", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6587829/pexels-photo-6587829.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 24", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/7061416/pexels-photo-7061416.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 25", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/7061423/pexels-photo-7061423.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 26", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6908355/pexels-photo-6908355.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 27", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/7061729/pexels-photo-7061729.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 28", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6890406/pexels-photo-6890406.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 29", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6301176/pexels-photo-6301176.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 30", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6301176/pexels-photo-6301176.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 31", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6933773/pexels-photo-6933773.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 32", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/7061067/pexels-photo-7061067.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 33", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6301171/pexels-photo-6301171.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 34", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/7061425/pexels-photo-7061425.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 35", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/7533924/pexels-photo-7533924.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 36", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/3678489/pexels-photo-3678489.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 37", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/7166939/pexels-photo-7166939.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 38", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6587893/pexels-photo-6587893.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 39", title: "Modern Bathroom", description: "Decor / Architecture" },
    { src: "https://images.pexels.com/photos/6538889/pexels-photo-6538889.jpeg?auto=compress&cs=tinysrgb&w=600&lazy=load", alt: "Bathroom 40", title: "Modern Bathroom", description: "Decor / Architecture" },
  ];